[package]
name = "xcp-metrics-tools"
description = "Various xcp-metrics utilities"
version = "0.1.0"
license = "AGPL-3.0-only"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xcp-metrics-common = { path = "../xcp-metrics-common" }
anyhow = "*"
serde_json = "1.0"
