[package]
name = "xcp-metrics-tools"
description = "Various xcp-metrics utilities"
version.workspace = true
license = "AGPL-3.0-only"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xcp-metrics-common = { path = "../xcp-metrics-common" }
anyhow = "*"
serde_json = "1.0"

tokio = { version = "1", features = ["full"] }

[dependencies.quick-xml]
version = "0.29"
features = ["serialize"]