[package]
name = "xcp-metrics"
description = "Main xcp-metrics daemon"
version = "0.1.0"
license = "AGPL-3.0-only"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xcp-metrics-common = { version = "*", path = "../xcp-metrics-common" }
serde_json = "1.0"
anyhow = "1.0"
dashmap = "5.4"
prost = "0.11"
prost-types = "0.11"

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.serde]
version = "1.0"
features = ["std", "derive"]

[build-dependencies]
prost-build = "0.11"

[dependencies.uuid]
version = "1.3"
features = ["std", "serde", "v4", "fast-rng"]
