[package]
name = "xcp-metrics"
description = "Main xcp-metrics daemon"
version.workspace = true
license = "AGPL-3.0-only"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xcp-metrics-common = { path = "../xcp-metrics-common" }
serde_json = "1.0"
anyhow = "1.0"
once_cell = "1.18"
futures = "0.3"
dashmap = "5.4.0"
tracing = "0.1"
tracing-subscriber = "0.3"
maplit = "1.0.2"

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.serde]
version = "1.0"
features = ["std", "derive"]

[dependencies.uuid]
version = "1.3"
features = ["std", "serde", "v4", "fast-rng"]

[dependencies.sendfd]
version = "0.4.3"
features = ["tokio"]

[dependencies.clap]
version = "4.3"
features = ["derive"]
