[package]
name = "xcp-metrics"
description = "Main xcp-metrics daemon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0"
anyhow = "1.0"
dashmap = "5.4"
xcp-metrics-common = { version = "*", path = "../xcp-metrics-common" }
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["full"] }

[dependencies.serde]
version = "1.0"
features = ["std", "derive"]
