[package]
name = "xen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = { version = "0.29", features = ["ioctl", "mman"] }
bitflags = { version = "2.6.0", default-features = false }
uuid = { workspace = true }
anyhow = { workspace = true }