[package]
name = "xcp-metrics-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc32fast = "1.3"
serde_json = "1.0"
anyhow = "1.0"
hyperlocal = "*"

[dependencies.serde]
version = "1.0"
features = ["std", "derive"]

[dependencies.uuid]
version = "1.3"
features = ["std", "serde"]

# XML-RPC stuff
[dependencies.dxr]
version = "0.5"
features = ["derive"]
default-features = false # no client/server stuff

[dependencies.quick-xml]
version = "*"
features = ["serialize"]

[dependencies.hyper]
version = "0.14"
features = ["full"]

[dependencies.tokio]
version = "1"
features = ["full"]
