[package]
name = "xcp-metrics-common"
description = "Library related to xcp-metrics and rrdd"
version.workspace = true
license = "AGPL-3.0-only"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc32fast = "1.3"
serde_json = "1.0"
anyhow = "1.0"
hyperlocal = "0.8"
jsonrpc-base = "0.2.0"

[dependencies.serde]
version = "1.0"
features = ["std", "derive"]

[dependencies.uuid]
version = "1.3"
features = ["std", "serde"]

[dependencies.indexmap]
version = "1.9"
features = ["serde"]

# XML-RPC stuff
[dependencies.dxr]
git = "https://github.com/ironthree/dxr.git"
rev = "72ed48961199da45e4bae472060ab7de09dbe291" # unwrapped string support
features = ["derive"]
default-features = false # no client/server stuff

[dependencies.quick-xml]
version = "0.29"
features = ["serialize"]

[dependencies.hyper]
version = "0.14"
features = ["full"]

[dependencies.tokio]
version = "1"
features = ["full"]
