[package]
name = "xcp-metrics-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "*"
xcp-metrics-common = { version = "*", path = "../xcp-metrics-common" }