name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      with:
        persist-credentials: false
    - run: rustup install stable
    - name: Installing dependency packages
      run: sudo apt update && sudo apt install -y libxen-dev protobuf-compiler

    - name: Build
      run: cargo build --verbose

  doc:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      with:
        persist-credentials: false
    - run: rustup install stable
    - name: Installing dependency packages
      run: sudo apt update && sudo apt install -y libxen-dev protobuf-compiler

    - name: Build docs
      run: cargo doc --workspace --no-deps

    - name: Upload docs
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: rustdoc-html
        path: ./target/doc

  test:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      with:
        persist-credentials: false
    - run: rustup install stable
    - name: Installing dependency packages
      run: sudo apt update && sudo apt install -y libxen-dev protobuf-compiler

    - name: Run tests
      run: |
        cargo clean
        cargo test --verbose
      env:
        CARGO_INCREMENTAL: '0'

    - name: Install cargo-llvm-cov
      run: cargo install cargo-llvm-cov
    - name: Test coverage report
      run: cargo llvm-cov --html --output-dir ./target/coverage

    - name: Upload test coverage report
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: coverage-html
        path: ./target/coverage/

  rustfmt:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      with:
        persist-credentials: false
    - run: rustup install stable --component rustfmt
    - run: cargo fmt --all --check

  clippy:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      with:
        persist-credentials: false
    - name: Installing dependency packages
      run: sudo apt update && sudo apt install -y libxen-dev protobuf-compiler
    - run: rustup install stable --component clippy
    - run: cargo clippy --all-targets -- -D warnings

  zizmor:
    name: zizmor
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@b75a909f75acd358c2196fb9a5f1299a9a8868a4 # v6.7.0
      - run: uvx zizmor .
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
