name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    #container:
    #  image: centos8 
    
    steps:
    - uses: dtolnay/rust-toolchain@1.69.0
    - uses: actions/checkout@v3
    - name: Preparing
      run: sudo apt update && sudo apt install -y libxen-dev protobuf-compiler

    - name: Build
      run: cargo build --verbose

    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov
    
    - name: Generate code coverage
      run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: lcov.info
        fail_ci_if_error: true
    
    - name: Run tests
      run: cargo test --verbose
